### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by n0thhhing** [AlexAltea/unicorn.js#47]
Seems to happen on every release(and yes I realize this probably hasn't been worked on for a while)

```shell
╰─❯ bun test.ts
229 |                         return function (_, _) {
                                                  ^
error: "_" cannot be bound multiple times in the same parameter list
    at /storage/self/primary/Download/projects/emu/unicorn.min.js:229:45

237 |                         return function (_, intno, _) {
                                                         ^
error: "_" cannot be bound multiple times in the same parameter list
    at /storage/self/primary/Download/projects/emu/unicorn.min.js:237:52

246 |                         return function (_, addr_lo, addr_hi, size, _) {

        ^
error: "_" cannot be bound multiple times in the same parameter list
    at /storage/self/primary/Download/projects/emu/unicorn.min.js:246:69

258 |                             return function (_, type, addr_lo, addr_hi, size, value_lo, value_hi, _) {

                       ^
error: "_" cannot be bound multiple times in the same parameter list
    at /storage/self/primary/Download/projects/emu/unicorn.min.js:258:99

271 |                             return function (_, type, addr_lo, addr_hi, size, value_lo, value_hi, _) {

                       ^
error: "_" cannot be bound multiple times in the same parameter list
    at /storage/self/primary/Download/projects/emu/unicorn.min.js:271:99

Bun v1.1.13 (Linux arm64)
```

**Comment by Jarred-Sumner** [comment]
Ah, this is an error when bundling for strict mode but we shouldn't be erroring on this at runtime unless a strict mode only feature was in use

**Comment by n0thhhing** [comment]
Yes most likely, looks like anything with "\_" followed by a number gets the number striped, which just leaves "\_", therefore cases where there's already a "\_" defined, it will create naming issues

i.e. [line 211](https://github.com/AlexAltea/unicorn.js/blob/master/src%2Funicorn-wrapper.js#L211) in unicorn-wrapper.js

**Comment by AlexAltea** [comment]
This should be fixed in the latest Unicorn.js release (tracking upstream Unicorn v2.1.4):
https://github.com/AlexAltea/unicorn.js/releases/tag/v2.1.4
